server:
  port: 2003
spring:
  datasource:
    url: jdbc:mysql://customer-db:3306/customer
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
